example/example/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^nublas/', include('nublas.urls', namespace='nublas')),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nublas/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView, RedirectView

from .conf import settings

from .ui.skins import get_skin_relative_path

from .ui.views.home import *
from .ui.views.agenda import *
from .ui.views.auth import *
from .ui.views.association import *
from .ui.views.contact import *


#==============================================================================
urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url=settings.INDEX_URL), name='home'),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    url(r'^tags/$', TagsAutoCompleteView.as_view(), name='tags'),
)


#==============================================================================
urlpatterns += patterns('',
    # association editing
    url(r'^association/list/$', AssociationListView.as_view(), name='association_list'),
    url(r'^association/add/$', AssociationAddView.as_view(), name='association_add'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/details/$', AssociationDetailsView.as_view(), name='association_details'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/edit/$', AssociationEditView.as_view(), name='association_edit'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/delete/$', AssociationDeleteView.as_view(), name='association_delete'),

    # association contacts handling
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/contacts/$', AssociationContactListView.as_view(), name='association_contacts'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/contacts/action/$', AssociationContactListActionView.as_view(), name='association_contacts_action'),

    # association file handling
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/files/$', AssociationFilesView.as_view(), name='association_files'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/fileserve/$', AssociationFileServeView.as_view(), name='association_fileserve'),

    # association agenda handling
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/agenda/$', AssociationAgendaView.as_view(), name='association_agenda'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/agenda/latest/$', AssociationAgendaLatestView.as_view(), name='association_agenda_latest'),

    # association custom fields
    #url(r'^(?P<association>[a-fA-F0-9]{32})/custom/$', AssociationCustomView.as_view(), name='association_custom'),
    #url(r'^(?P<association>[a-fA-F0-9]{32})/custom/add/$', AssociationCustomAddView.as_view(), name='association_custom_add'),
    #url(r'^custom/(?P<object>[a-fA-F0-9]{32})/edit/$', AssociationCustomEditView.as_view(), name='association_custom_edit'),
    #url(r'^custom/(?P<object>[a-fA-F0-9]{32})/delete/$', AssociationCustomDeleteView.as_view(), name='association_custom_delete'),

    # association settings
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/settings/$', AssociationSettingsView.as_view(), name='association_settings'),

    # TODO - add specific settings
)


#==============================================================================
urlpatterns += patterns('',
    # globals
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/contact/add/$', ContactAddView.as_view(), name='contact_add'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/contact/autocomplete/$', ContactAutoCompleteView.as_view(), name='contact_search_autocomplete'),

    # details
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/details/$', ContactDetailsView.as_view(), name='contact_details'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/edit/$', ContactEditView.as_view(), name='contact_edit'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/delete/$', ContactDeleteView.as_view(), name='contact_delete'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/files/$', ContactFilesView.as_view(), name='contact_files'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/fileserve/$', ContactFileServeView.as_view(), name='contact_fileserve'),

    # addresses
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/address/add/$', ContactAddressAddView.as_view(), name='contact_address_add'),
    url(r'^contact/address/(?P<object>[a-fA-F0-9]{32})/edit/$', ContactAddressEditView.as_view(), name='contact_address_edit'),
    url(r'^contact/address/(?P<object>[a-fA-F0-9]{32})/delete/$', ContactAddressDeleteView.as_view(), name='contact_address_delete'),

    # phones
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/phone/add/$', ContactPhoneAddView.as_view(), name='contact_phone_add'),
    url(r'^contact/phone/(?P<object>[a-fA-F0-9]{32})/edit/$', ContactPhoneEditView.as_view(), name='contact_phone_edit'),
    url(r'^contact/phone/(?P<object>[a-fA-F0-9]{32})/delete/$', ContactPhoneDeleteView.as_view(), name='contact_phone_delete'),

    # emails
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/email/add/$', ContactEmailAddView.as_view(), name='contact_email_add'),
    url(r'^contact/email/(?P<object>[a-fA-F0-9]{32})/edit/$', ContactEmailEditView.as_view(), name='contact_email_edit'),
    url(r'^contact/email/(?P<object>[a-fA-F0-9]{32})/delete/$', ContactEmailDeleteView.as_view(), name='contact_email_delete'),

    # websites
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/websites/add/$', ContactWebsiteAddView.as_view(), name='contact_website_add'),
    url(r'^contact/websites/(?P<object>[a-fA-F0-9]{32})/edit/$', ContactWebsiteEditView.as_view(), name='contact_website_edit'),
    url(r'^contact/websites/(?P<object>[a-fA-F0-9]{32})/delete/$', ContactWebsiteDeleteView.as_view(), name='contact_website_delete'),

    # groups
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/groups/$', ContactGroupView.as_view(), name='contact_groups'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/group/add/$', ContactGroupAddView.as_view(), name='contact_group_add'),
    url(r'^contact/group/(?P<object>[a-fA-F0-9]{32})/edit/$', ContactGroupEditView.as_view(), name='contact_group_edit'),
    url(r'^contact/group/(?P<object>[a-fA-F0-9]{32})/delete/$', ContactGroupDeleteView.as_view(), name='contact_group_delete'),

    # subscriptions
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/subscriptions/$', ContactSubscriptionView.as_view(), name='contact_subscriptions'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/subscription/add/$', ContactSubscriptionAddView.as_view(), name='contact_subscription_add'),
    url(r'^contact/subscription/(?P<object>[a-fA-F0-9]{32})/edit/$', ContactSubscriptionEditView.as_view(), name='contact_subscription_edit'),
    url(r'^contact/subscription/(?P<object>[a-fA-F0-9]{32})/delete/$', ContactSubscriptionDeleteView.as_view(), name='contact_subscription_delete'),

    # partecipations
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/partecipations/$', ContactPartecipationView.as_view(), name='contact_partecipations'),

    # relationships
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/relationships/$', ContactRelationshipView.as_view(), name='contact_relationships'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/relationship/add/$', ContactRelationshipAddView.as_view(), name='contact_relationship_add'),
    url(r'^contact/relationship/(?P<object>[a-fA-F0-9]{32})/edit/$', ContactRelationshipEditView.as_view(), name='contact_relationship_edit'),
    url(r'^contact/relationship/(?P<object>[a-fA-F0-9]{32})/delete/$', ContactRelationshipDeleteView.as_view(), name='contact_relationship_delete'),

    # reverse relationships
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/relationships/rev/$', ContactReverseRelationshipView.as_view(), name='contact_reverse_relationships'),
    url(r'^contact/(?P<contact>[a-fA-F0-9]{32})/relationship/rev/add/$', ContactReverseRelationshipAddView.as_view(), name='contact_reverse_relationship_add'),
    url(r'^contact/relationship/(?P<object>[a-fA-F0-9]{32})/rev/edit/$', ContactReverseRelationshipEditView.as_view(), name='contact_reverse_relationship_edit'),
    url(r'^contact/relationship/(?P<object>[a-fA-F0-9]{32})/rev/delete/$', ContactReverseRelationshipDeleteView.as_view(), name='contact_reverse_relationship_delete'),
)


#==============================================================================
urlpatterns += patterns('',
    # events from all associations (in dashboard)
    url(r'^events/$', AgendaAllEventListJsonView.as_view(), name='agenda_allevents'),
    url(r'^events/style.css$', AgendaAllEventListCssView.as_view(), name='agenda_allevents_style'),

    # association events
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/events/$', AgendaEventListJsonView.as_view(), name='agenda_events'),
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/events/style.css$', AgendaEventListCssView.as_view(), name='agenda_events_style'),

    # events manipulation
    url(r'^association/(?P<association>[a-fA-F0-9]{32})/event/add/$', AgendaEventAddView.as_view(), name='agenda_event_add'),
    url(r'^event/(?P<object>[a-fA-F0-9]{1,32})/edit/$', AgendaEventEditView.as_view(), name='agenda_event_edit'),
    url(r'^event/(?P<object>[a-fA-F0-9]{1,32})/resize/$', AgendaEventResizeView.as_view(), name='agenda_event_resize'),
    url(r'^event/(?P<object>[a-fA-F0-9]{1,32})/delete/$', AgendaEventDeleteView.as_view(), name='agenda_event_delete'),
)


#==============================================================================
# Only enable login based urls if requested
if settings.ENABLE_USER_LOGIN:
    urlpatterns += patterns('',
        # profile login
        url(r'^auth/login/$', LoginView.as_view(), name='auth_login'),
        url(r'^auth/logout/$', LogoutView.as_view(), name='auth_logout'),

        # user profile editing
        url(r'^auth/profile/$', ProfileView.as_view(), name='auth_profile'),

        # lost password and username
        url(r'^auth/lost_password/$', LostPasswordView.as_view(), name='auth_lost_password'),
        url(r'^auth/lost_password_change/(?P<lost_password_key>.*)/$', LostPasswordChangeView.as_view(), name='auth_lost_password_change'),

nublas/db/models/agenda.py
import re
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _

from ...conf import settings
from ..base import BaseModel
from ..fields import color
from .utils import BaseModelLinkedToAssociation

__all__ = [ "Calendar", "Event", "ContactAppointment" ]


#==============================================================================
@python_2_unicode_compatible
class Calendar(BaseModelLinkedToAssociation('calendars')):
    name = models.CharField(_('name'), max_length=50)
    colour = color.RGBColorField(_('colour'), default='#ff0000')
    is_public = models.BooleanField(_('is public'), default=True)
    is_enabled = models.BooleanField(_('is enabled'), default=True)

    #def colored_list(self):
    #    return '<div style="width:16px;height:16px;background-color: %s;border:1px solid #CCCCCC;"></div>' % (self.colour)
    #colored_list.allow_tags = True
    #colored_list.admin_order_field = 'colour'
    #colored_list.short_description = _('Colour')

    class Meta:
        verbose_name = _("calendar")
        verbose_name_plural = _("calendars")

    def unique_identifier(self):
        calendar_name = '%s-%s' % (self.name, self.uuid)
        return re.sub(r'\s', '-', calendar_name).lower() # TODO - strip spaces

    def __str__(self):
        if self.is_public:
            return _("%(name)s (Public)") % {'name': self.name}
        else:
            return self.name


#==============================================================================
@python_2_unicode_compatible
class Event(BaseModel):
    title = models.CharField(_('title'), max_length=200)
    details = models.TextField(_('details'), blank=True, null=True)
    calendar = models.ForeignKey('nublas.Calendar', default=1, limit_choices_to = { 'is_enabled__exact': True }, verbose_name=_('calendar'))
    start_date = models.DateTimeField(_('start date'))
    end_date = models.DateTimeField(_('end date'))
    allday = models.BooleanField(_('all day'), default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='event_owner', null=True, blank=True, verbose_name=_('owner'))
    contacts = models.ManyToManyField('nublas.Contact', through='nublas.ContactAppointment', related_name='events', verbose_name=_('contacts'))
    # TODO - dogs should be visible only if we have the constraint
    #dogs = models.ManyToManyField('backend.Dog', through='DogAppointment', related_name='events', verbose_name=_('dogs'))
    # TODO - public registration boolean
    # TODO - expected cost float
    # TODO - payed boolean

    class Meta:
        verbose_name = _("event")
        verbose_name_plural = _("events")

    def save(self, *args, **kwargs):
        if self.end_date is None:
            self.end_date = self.start_date
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % self.title


#==============================================================================
@python_2_unicode_compatible
class ContactAppointment(BaseModel):
    event = models.ForeignKey('nublas.Event', verbose_name=_('event'))
    contact = models.ForeignKey('nublas.Contact', verbose_name=_('contact'))
    info = models.TextField(_('info'), blank=True, null=True)
    #price = fields.CurrencyField(_('price'),blank=True, null=True)
    #payed = models.BooleanField(_('payed'), default=True)
    attended = models.BooleanField(_('attended'), default=True)

    class Meta:
        verbose_name = _("contact appointment")
        verbose_name_plural = _("contact appointments")

    def __str__(self):
        return _("%(last_name)s %(first_name)s") % {
            'last_name': self.contact.last_name,
            'first_name': self.contact.first_name }

nublas/ui/views/home.py
import json
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils import timezone, translation
from django.utils.translation import ugettext_lazy as _
from django.utils.decorators import method_decorator
from django.shortcuts import render_to_response, get_object_or_404
from django.views.generic.base import View, TemplateView

from taggit.models import Tag

from ...conf import settings
from ...models import Contact
from ..skins import get_skin_relative_path

import logging
logger = logging.getLogger(__name__)

__all__ = [ "Custom403View", "Custom404View", "Custom500View",
            "HomeView", "DashboardView", "TagsAutoCompleteView" ]


#==============================================================================
def Custom403View(request):
    return render_to_response(get_skin_relative_path('403.html'),
                              RequestContext(request, { }))

def Custom404View(request):
    return render_to_response(get_skin_relative_path('404.html'),
                              RequestContext(request, { }))

def Custom500View(request):
    return render_to_response(get_skin_relative_path('500.html'),
                              RequestContext(request, { }))


#==============================================================================
class HomeView(TemplateView):
    template_name = get_skin_relative_path("views/home/index.html")


#==============================================================================
class DashboardView(View):
    #@method_decorator(login_required(login_url=settings.LOGIN_URL))
    def dispatch(self, request, *args, **kwargs):
        # wrong configuration ?
        #if request.user.constraint_value("max_associations") == 0:
        #    messages.error(request, _('Something is wrong in your configuration. Please contact the administrator.'))
        #    return HttpResponseRedirect(reverse('backend:home'))

        # if no associations then redirect to add a first association
        #if not Association.objects.filter(Q(holder=request.user)).exists():
        #    messages.info(request, _('You need to create an association to continue.'))
        #    return HttpResponseRedirect(reverse('association:add'))

        # query data for the dashboard
        filter_contacts = Q(association__holder=request.user) | Q(association__collaborators=request.user)
        latest_contacts = Contact.objects.filter(filter_contacts).order_by("-_created")

        return render_to_response(get_skin_relative_path('views/dashboard/index.html'),
                                  RequestContext(request, { 'latest_contacts': latest_contacts }))


#==============================================================================
# TODO - use cache_page with at least a 30 min cache
class TagsAutoCompleteView(View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        result = []
        searchtext = request.GET['term']
        if len(searchtext) >= 2:
            tags = Tag.objects.filter(name__icontains=searchtext).order_by('name')[:10]
            for t in tags:
                result.append({ 'id': t.pk, 'label': str(t.name), 'value': str(t.name) }) # TODO - handle uuid ?

        return HttpResponse(json.dumps(result))

nublas/templates/nublas/skins/default/views/contact/details.html
{% nublas_extends "base_site.html" %}
{% load i18n %}


{% block javascript-extra %}
    <script type="text/javascript">
        (function($){
            $(document).ready(function(){

                //===== Delete rows =====//

                var postForm = function(elem) {
                    $('<form>', {
                        'action': $(elem).attr('href'),
                        'method': 'POST',
                        'target': '_top'
                    }).append($('<input>', {
                        'type': 'hidden',
                        'name': 'csrfmiddlewaretoken',
                        'value': '{{ csrf_token }}'
                    })).appendTo('body').submit();
                };

                $(".nublas-contact-address-table .nublas-delete-button").click(function(e){
                    e.preventDefault();
                    bootbox.confirm(
                        "{% trans 'Are you sure you want to delete the address ?' %}",
                        $.proxy(function(result) {
                            if (result)
                                postForm(this);
                        }, $(this));
                    );
                });

                $(".nublas-contact-email-table .nublas-delete-button").click(function(e){
                    e.preventDefault();
                    bootbox.confirm(
                        "{% trans 'Are you sure you want to delete the email ?' %}",
                        $.proxy(function(result) {
                            if (result)
                                postForm(this);
                        }, $(this));
                    );
                });

                $(".nublas-contact-phone-table .nublas-delete-button").click(function(e){
                    e.preventDefault();
                    bootbox.confirm(
                        "{% trans 'Are you sure you want to delete the phone number ?' %}",
                        $.proxy(function(result) {
                            if (result)
                                postForm(this);
                        }, $(this));
                    );
                });

                $(".nublas-contact-website-table .nublas-delete-button").click(function(e){
                    e.preventDefault();
                    bootbox.confirm(
                        "{% trans 'Are you sure you want to delete the website ?' %}",
                        $.proxy(function(result) {
                            if (result)
                                postForm(this);
                        }, $(this));
                    );
                });

            });
        })(jQuery);
    </script>
{% endblock %}


{% block content-title %}
    <div class="page-header">
        {% if adding %}
            <h1>{% trans "Adding new contact" %}</h1>
        {% else %}
            <h1>{{ contact.first_name }} {{ contact.last_name }}
                <small>{% trans "Contact details" %}
                    {% if editing %}
                        <a href="{% url 'nublas:contact_details' contact.uuid %}" class="btn btn-default btn-xs">
                            <i class="fa fa-eye fa-fw"></i> {% trans "View" %}</a>
                    {% else %}
                        <a href="{% url 'nublas:contact_edit' contact.uuid %}" class="btn btn-primary btn-xs">
                            <i class="fa fa-pencil fa-fw"></i> {% trans "Edit" %}</a>
                    {% endif %}
                </small>
            </h1>
        {% endif %}
    </div>
{% endblock %}


{% block content-breadcrumb-inner %}
    <li><a href="{% url 'nublas:home' %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'nublas:association_list' %}">{% trans "Associations" %}</a></li>
    {% if not adding %}
        <li><a href="{% url 'nublas:association_details' contact.association.uuid %}">{{ contact.association.name|capfirst }}</a></li>
        <li><a href="{% url 'nublas:association_contacts' contact.association.uuid %}">{% trans "Contacts" %}</a></li>
        <li class="active">{{ contact.first_name }} {{ contact.last_name }}</li>
    {% else %}
        <li class="active">{% trans "Add contact" %}</li>
    {% endif %}
{% endblock %}


{% block content-inner %}

    <form action="." method="POST" class="form-horizontal" role="form">{% csrf_token %}

        <ul class="nav nav-tabs" role="tablist">
            {% nublas_include "views/contact/tabs.html" with activetab="details" %}
        </ul>

        <div class="tab-content">

            <!-- Personal details -->
            <div class="tab-pane active">

                <!-- Main form -->
                {% nublas_include "generic/form_snippet.html" with form=personal_form %}

                <!-- Other infos -->
                {% if contact %}
                <div class="form-group">
                    <!-- Addresses -->
                    <label class="col-sm-2 control-label">
                        {% trans 'Addresses' %}
                    </label>
                    <div class="col-sm-4">
                        {% nublas_include "views/contact/tables/addresses.html" with addresses=contact.addresses.all %}
                    </div>

                    <!-- Phone numbers -->
                    <label class="col-sm-2 control-label">
                        {% trans 'Phones' %}
                    </label>
                    <div class="col-sm-4">
                        {% nublas_include "views/contact/tables/phones.html" with phones=contact.phones.all %}
                    </div>
                </div>

                <div class="form-group">
                    <!-- Emails -->
                    <label class="col-sm-2 control-label">
                        {% trans 'Emails' %}
                    </label>
                    <div class="col-sm-4">
                        {% nublas_include "views/contact/tables/emails.html" with emails=contact.emails.all %}
                    </div>

                    <!-- Websites -->
                    <label class="col-sm-2 control-label">
                        {% trans 'Websites' %}
                    </label>
                    <div class="col-sm-4">
                        {% nublas_include "views/contact/tables/websites.html" with websites=contact.websites.all %}
                    </div>
                </div>
                {% endif %}

                <!-- Custom form fields -->
                {% if custom_form and custom_form.fields|length > 0 %}
                    {% nublas_include "generic/form_snippet.html" with form=custom_form %}
                {% endif %}

                <!-- Buttons -->
                {% if editing or adding %}
                <div class="form-group">
                    <div class="col-sm-12">
                        <div class="pull-left">
                            <button class="btn btn-primary btn-sm" type="submit">
                                <i class="fa fa-floppy-o fa-fw"></i> {% trans 'Save Contact' %}</button>
                            <a class="btn btn-default btn-sm" href="#">
                                {% trans "Save and add another" %}</a>
                            {% if not adding %}
                            <a class="btn btn-default btn-sm" href="#">
                                {% trans "Save as a copy" %}</a>
                            {% endif %}
                        </div>

                        {% if editing and not adding %}
                        <div class="pull-right">
                            <a class="btn btn-danger btn-sm" href="{% url 'nublas:contact_delete' contact.uuid %}">
                                <i class="fa fa-close fa-fw"></i> {% trans "Delete" %}</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endif %}

            </div>

            {% if contact %}
            <!-- Groups -->
            <div class="tab-pane" id="groups">
                {% nublas_include "views/contact/tables/groups.html" with groups=contact.groups.all %}
            </div>
            {% endif %}
        </div>

    </form>

{% endblock %}

nublas/templates/nublas/skins/default/views/contact/files.html
{% nublas_extends "base_site.html" %}
{% load i18n %}

{% block javascript-after %}
    {% nublas_include "views/files/script.html" %}
{% endblock %}


{% block content-title %}
    <div class="page-header">
        <h1>{{ contact.first_name }} {{ contact.last_name }} <small>{% trans "Contact files" %}</small></h1>
    </div>
{% endblock %}


{% block content-breadcrumb-inner %}
    <li><a href="{% url 'nublas:home' %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'nublas:association_list' %}">{% trans "Associations" %}</a></li>
    <li><a href="{% url 'nublas:association_details' contact.association.uuid %}">{{ contact.association.name|capfirst }}</a></li>
    <li><a href="{% url 'nublas:association_contacts' contact.association.uuid %}">{% trans "Contacts" %}</a></li>
    <li><a href="{% url 'nublas:contact_details' contact.uuid %}">{{ contact.first_name }} {{ contact.last_name }}</a></li>
    <li class="active">{% trans "Files" %}</li>
{% endblock %}


{% block content-inner %}
    <ul class="nav nav-tabs" role="tablist">
        {% nublas_include "views/contact/tabs.html" with activetab="files" %}
    </ul>

    <div class="tab-content">
        <div class="tab-pane active">
            <input type="hidden" id="fileserve-url" value="{% url 'nublas:contact_fileserve' contact.uuid %}" />
            {% nublas_include "views/files/content.html" %}
        </div>
    </div>
{% endblock %}

nublas/templates/nublas/skins/default/views/contact/tabs.html
{% load i18n %}

<li {% if activetab == 'details' %}class="active"{% endif %}>
    <a href="{% if activetab != 'details' %}{% url 'nublas:contact_details' contact.uuid %}{% else %}#{% endif %}" role="tab">
        {% trans "Personal details" %}</a></li>

{% if contact and not adding %}
<li {% if activetab == 'groups' %}class="active"{% endif %}>
    <a href="{% if activetab != 'groups' %}{% url 'nublas:contact_groups' contact.uuid %}{% else %}#{% endif %}" role="tab">
        {% trans "Groups" %}</a></li>
<li {% if activetab == 'subscriptions' %}class="active"{% endif %}>
    <a href="{% if activetab != 'subscriptions' %}{% url 'nublas:contact_subscriptions' contact.uuid %}{% else %}#{% endif %}" role="tab">
        {% trans "Subscriptions" %}</a></li>
<li {% if activetab == 'partecipations' %}class="active"{% endif %}>
    <a href="{% if activetab != 'partecipations' %}{% url 'nublas:contact_partecipations' contact.uuid %}{% else %}#{% endif %}" role="tab">
        {% trans "Partecipations" %}</a></li>
<li {% if activetab == 'relationships' %}class="active"{% endif %}>
    <a href="{% if activetab != 'relationships' %}{% url 'nublas:contact_relationships' contact.uuid %}{% else %}#{% endif %}" role="tab">
        {% trans "Relationships" %}</a></li>
<li {% if activetab == 'files' %}class="active"{% endif %}>
    <a href="{% if activetab != 'files' %}{% url 'nublas:contact_files' contact.uuid %}{% else %}#{% endif %}" role="tab">
        {% trans "Files" %}</a></li>
{% endif %}